server:
  port: 9001
spring:
  application:
    name: config-client
  cloud:
    config: #Config客户端配置
          uri: http://localhost:8901 #配置中心地址
          profile: dev #启用配置后缀名称
          label: main #分支名称
          name: config #配置文件名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
