server:
  port: 9500
spring:
  application:
    name: nacos-user-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
      config:
        server-addr: localhost:8848 #Nacos地址
        file-extension: yaml #这里我们获取的yaml格式的配置

management:
  endpoints:
    web:
      exposure:
        include: '*'

